title: <p align="center"> Yogeshwara Ranjith </p>
logo: /assets/img/logo.png

description:
  <p align="center"> |
  <a href="https://www.linkedin.com/in/ranjith-yogeshwara-5a91131b8/">LinkedIn</a> |
  <a href="https://github.com/yogeshwararanjith">GitHub</a>
  
  <br>   
  I'm working on Angular, Java, Spring and Python 
  <br>
  </p>



theme: jekyll-theme-minimal
